language: node_js
sudo: false

os:
  - windows
  - linux
  - osx

git:
  depth: 10

node_js:
  - "6"
  - "8"
  - "10"

install:
  - npm install
  - npm install -g codecov

before_script:
  - echo "Node Version: `node -v`"
  - echo "NPM Version: `npm -v`"
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then echo "MSBuild Version: `msbuild -version -nologo`"; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then echo "MSBuild Path: `where msbuild`"; fi

script:
  - npm run cover
  # - IF NOT EXIST "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" ( echo "no vswhere" ) ELSE "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere" -property installationPath -products * -all"
  # - IF NOT EXIST "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" ( echo "no vswhere" ) ELSE "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere" -property installationPath -all"
  # - IF NOT EXIST "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" ( echo "no vswhere" ) ELSE "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere" -property installationPath -legacy"

after_script:
  - codecov