language: node_js
sudo: false

os:
  - windows
  - linux
  - osx

git:
  depth: 10

node_js:
  - "6"
  - "8"
  - "10"

install:
  - npm install
  - npm install -g codecov

before_script:
  - node -v
  - npm -v
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then msbuild -version -nologo; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then where msbuild; fi

script:
  - npm run test:coverage

after_script:
  - codecov