language: node_js
sudo: false

os:
  - windows
  # - linux
  # - osx

git:
  depth: 10

node_js:
  # - "6"
  # - "8"
  - "10"

install:
  - npm install
  - npm install -g codecov

before_script:
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then dotnet --info; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ls "C:\Program Files"; fi
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then "C:\ProgramData\Microsoft Visual Studio\Installer\vswhere" -property installationPath -products * -all; fi
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then "C:\ProgramData\Microsoft Visual Studio\Installer\vswhere" -property installationPath -all; fi
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then "C:\ProgramData\Microsoft Visual Studio\Installer\vswhere" -property installationPath -legacy; fi
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then echo "MSBuild Path = C:\ProgramData\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe"; fi
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then "C:\ProgramData\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe" -version -nologo; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then npm run test:coverage:win; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then npm run test:coverage; fi

after_script:
  - codecov