language: node_js
sudo: false

os:
  - windows
  # - linux
  # - osx

git:
  depth: 10

node_js:
  # - "6"
  # - "8"
  - "10"

install:
  - npm install
  - npm install -g codecov

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then dotnet --info; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell msbuild -version -nologo; fi
  

script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell npm run test:coverage:win; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then npm run test:coverage; fi

after_script:
  - codecov